In [1]:
import numpy as np
from ase import io
from ralign import options, routines

In [2]:
def lblstr(string):
    return string + (options.lbllen - len(string))*' '

def optstr(string):
    return string + (options.optlen - len(string))*' '

In [4]:
atoms0 = io.read('r005/100cobalt_j5.xyz', index=0)
atoms1 = io.read('r005/100cobalt_j5.xyz', index=1)

labels0 = np.empty((len(atoms0), options.lbllen), dtype='c')
for i, symbol in enumerate(atoms0.get_chemical_symbols()):
    labels0[i] = lblstr(symbol)
    
labels1 = np.empty((len(atoms1), options.lbllen), dtype='c')
for i, symbol in enumerate(atoms1.get_chemical_symbols()):
    labels1[i] = lblstr(symbol)

coords0 = np.transpose(atoms0.get_positions())
coords1 = np.transpose(atoms1.get_positions())

In [4]:
options.remap = True
options.biased = True
options.testing = True
options.matching = True
options.iterative = True
options.maxmatch = 10
options.biasscale = 1000.0
options.tolerance = 0.17
options.weighter = optstr('none')

routines.superpose(labels0, labels1, coords0, coords1, 10)

(10,
 array([-3.3e-07,  5.0e-08,  3.0e-07]),
 array([-3.25900e-05,  1.77807e-03, -6.13900e-03]),
 array([[ 35,  12,  60,  60,   5,  51,  93,  32,  84,  57],
        [ 68,  38,   6,   6,  87,  87,  87,   6,   6,  87],
        [ 27,  82,  13,  13,  23,  75,  78,   7,  11,  56],
        [ 31,  72,  42,  42,  85,  52,  22,  97,  97,  22],
        [ 24,  73,  69,  69,  83,  98,  80,  92,  61,  65],
        [ 70,  16,  67,  67,   4,  49,  39,  95,  95,  39],
        [ 25,  36,  38,  38,  25,  25,  38,  25,  25,  78],
        [ 75,   5,  10,  10,  45,  11,  82,  11,  27,  32],
        [  4,  67,  39,  39,  95,  79,  56,  70,   7,  16],
        [ 41,  51,  53,  19,  48,  12,  84,   9,  93,  34],
        [ 94,  28,  81,  81,  43,  48,  91,  29,  21,  37],
        [ 71,  79,   8,   8,   2,  67,   7,  49,  56,  74],
        [ 84,  93,  98,  98,  33,  35,  41,  62,  51,  17],
        [ 47,  47,  64,  64,  20,  65,  65,  64,  92,  20],
        [ 83,  69,  65,  65,  92,  29,  14,  24,  76,  73],
   